name: FromDoppler

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master", "INT"]
    tags:
      - v*.*.*

jobs:
  dotnet:
    name: .NET
    uses: FromDoppler/.github/.github/workflows/dotnet.yml@main
  docker:
    if: ${{ github.event_name == 'push' }}
    name: Docker
    uses: FromDoppler/.github/.github/workflows/continuous-delivery-dockerfile.yml@main
    secrets: inherit
    with:
      dockerfile-path: "Dockerfile"
      docker-image-name: "doppler-custom-domain"
